
#define MAX_PACKET_BUFFER_LEN	0x100000

#define SERVER_REQUIRE															0x100
#define CLIENT_RESPONSE															0x200
#define CLIENT_NOTIFICATION														0x300
#define SERVER_RESPONSE															0x400

#define SERVER_REQUIRE_GET_HARDWARE_INFO										SERVER_REQUIRE + 1
#define SERVER_REQUIRE_CLIENT_START_SOFTWARE_SNIFF								SERVER_REQUIRE + 2
#define SERVER_REQUIRE_CLIENT_STOP_SOFTWARE_SNIFF								SERVER_REQUIRE + 3
#define SERVER_REQUIRE_SET_HARDWARE_PERMISSIONS									SERVER_REQUIRE + 4
#define SERVER_REQUIRE_SET_SOFTWARE_PERMISSIONS									SERVER_REQUIRE + 5

#define CLIENT_RESPONSE_AUTH_KEY_FAIL											CLIENT_RESPONSE + 0x80
#define CLIENT_RESPONSE_MACHINE_DATA											CLIENT_RESPONSE + 1
#define CLIENT_RESPONSE_SET_HARDWARE_PERMISSIONS_RESULT							CLIENT_RESPONSE + 2
#define CLIENT_RESPONSE_SET_SOFTWARE_PERMISSIONS_RESULT							CLIENT_RESPONSE + 3

#define CLIENT_NOTIFICATION_REGISTER											CLIENT_NOTIFICATION + 1
#define CLIENT_NOTIFICATION_LOGIN												CLIENT_NOTIFICATION + 2
#define CLIENT_NOTIFICATION_KEYBOARD_EVENT										CLIENT_NOTIFICATION + 3
#define CLIENT_NOTIFICATION_KEYLOGGER_DETECTED									CLIENT_NOTIFICATION + 4 
#define CLIENT_NOTIFICATION_MEMORY_SERIAL_CHANGED								CLIENT_NOTIFICATION + 5 
#define CLIENT_NOTIFICATION_SOFTWARE_RUNNING									CLIENT_NOTIFICATION + 6


#define SERVER_RESPONSE_WELCOME													SERVER_RESPONSE + 0x80
#define SERVER_RESPONSE_REGISTERED												SERVER_RESPONSE + 1