
#ifndef _GLDSIOCTL_
#define _GLDSIOCTL_


#define FILE_DEVICE_PROTECT 0x00008000

#define NETCOPSVERSION    100

#define PROTECT_IOCTL_INDEX 0x800

#define IOCTL_BLOCK_ALL_DEVICE_INST		CTL_CODE( FILE_DEVICE_PROTECT, PROTECT_IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_UNBLOCK_ALL_DEVICE_INST	CTL_CODE( FILE_DEVICE_PROTECT, PROTECT_IOCTL_INDEX + 1, METHOD_BUFFERED, FILE_ANY_ACCESS )

#endif
